apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaServiceAccount
metadata:
  name: llm-plugin
  namespace: grafana-llm
spec:
  instanceName: grafana
  name: llm-plugin
  role: Viewer
  tokens:
    - name: tool-calling
      secretName: llm-sa-token
